routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\RealisationController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\AdminController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[PublicController::class,'index'])->name('accueil');
Route::get('realisations',[PublicController::class,'realisations'])->name('realisations');
Route::view('maconnerie','pages.default.maçonnerie')->name('maçonnerie');
Route::view('taille-de-pierre','pages.default.taille')->name('taille');
Route::view('contactez-moi','pages.default.contact')->name('contact');
Route::view('mentions','pages.default.mentions')->name('mentions');
Route::post('sendmail',[PublicController::class,'sendmail'])->name('sendmail');

Route::prefix('admin')->group(function () {
	Auth::routes();
	Route::middleware('auth')->group(function () {
		Route::view('/','pages.admin.index')->name('admin-index');
		Route::resource('categories', CategoriesController::class);
		Route::resource('realisations', RealisationController::class);
		Route::get('user',[AdminController::class,'mdp'])->name('user');
		Route::post('recup',[AdminController::class,'recup'])->name('recup');
		Route::post('delete-photo',[RealisationController::class,'deletephoto']);
	});
});

Route::get('/lang',[PublicController::class,'lang'])->name('lang');

resources/views/layout/admin.blade.php
<!doctype html>
<html lang="fr">

<head>
	<title>ADMIN - @yield('title'){{config('app.name')}}</title>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
	<!-- Material Kit CSS -->
	<link href="{{ asset('/css/material-dashboard.min.css') }}" rel="stylesheet" />
	<script src="{{ asset('js/app.js') }}"></script>
	<script src="{{ asset('js/ajax.js') }}"></script>

</head>

<body>
	<div class="wrapper ">
		<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
			<div class="logo">
				<span class="simple-text logo-normal">
					L'Art de la Pierre
				</span>
			</div>
			<div class="sidebar-wrapper">
				<ul class="nav text-center">
					@if(Auth::check())

					<li class="nav-item">
						<a class="nav-link" href="{{ route('admin-index') }}">Accueil</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ route('realisations.index') }}">Réalisations</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ route('categories.index') }}">Catégories</a>
					</li>
					<li class="nav-item active-pro">
						<form method="POST"action="{{ route('logout') }}">
							@csrf
							<button type="submit"class="nav-link btn btn-link">Déconnexion</button>
						</form>
					</li>
					<li class="nav-item ">
					<a class="btn btn-link" href="{{ route('user') }}">
						{{ __('Changer de Mot de passe') }}
					</a>
					</li>
					@else
					<li class="nav-item">
						<a class="nav-link" href="{{ route('accueil') }}">Revenir au site</a>
					</li>

					<!-- Navbar -->

					@endif

				</ul>
			</div>
		</div>
		<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
			<div class="container-fluid">

				<button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
					<span class="sr-only">Toggle navigation</span>
					<span class="navbar-toggler-icon icon-bar"></span>
					<span class="navbar-toggler-icon icon-bar"></span>
					<span class="navbar-toggler-icon icon-bar"></span>
				</button>

			</div>
		</nav>



		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-12">
							@yield('content')
						</div>
					</div>
				</div>
			</div>
			<footer class="footer">
				<div class="container-fluid">
				</div>
			</footer>
		</div>
	</div>

</body>
</html>

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="@lang('layout.title')">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@yield('title'){{config('app.name')}}</title>
	<link rel="icon" href="{{ asset('images/Logo.png') }}" type="image/png">

	<!-- LARAVEL -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	{{-- CSS --}}
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
	<link rel="stylesheet" href="{{ mix('css/app.css') }}">


	{{-- JS --}}
	<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
	<script src="{{ mix('js/app.js') }}" defer></script>
	{{-- <script src="{{ mix('js/lazy-load.js') }}"></script> --}}

	@yield('includes')
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-DPFGZGSQ2B"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());
		gtag('config', 'G-DPFGZGSQ2B');
	</script>
</head>
<body>
	<div id="carouselExampleSlidesOnly" class="carousel slide carousel-fade " data-ride="carousel" data-interval="7000">
		<div class="carousel-inner">
			<div class="caption w-100 d-flex justify-content-center">
				<div class="blur">
					<img class="" src="{{ asset('images/Logoblack.png') }}">
				</div>
			</div>
			<div class="carousel-item active">
				<img class="d-block" src="{{ asset('images/load.gif') }}" data-src="{{ asset('images/default/carousel3.jpg') }}" alt="Creation d'un mur par l Art de la pierre">
			</div>
			<div class="carousel-item">
				<img class="d-block" src="{{ asset('images/load.gif') }}" data-src="{{ asset('images/default/carousel2.jpg') }}" alt="Renovation toit par l Art de la pierre">
			</div>
			<div class="carousel-item">
				<img class="d-block" src="{{ asset('images/load.gif') }}" data-src="{{ asset('images/default/carousel1.jpg') }}" alt="Renovation d'une terrasse par l Art de la pierre">
			</div>
		</div>
	</div>

	<nav class="navbar navbar-expand-lg navbar-light sticky-top">
		<a class="navbar-brand" href="#">
			<img class="" src="{{ asset('images/Logoblack.png') }}">
		</a>

		<button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{{ route('accueil') }}">@lang('layout.accueil')</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ route('realisations') }}">@lang('layout.rea')</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ route('taille') }}">@lang('layout.taille')</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ route('maçonnerie') }}">@lang('layout.maçonnerie')</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ route('contact') }}">@lang('layout.cont')</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" href="{{ route('lang') }}" title="@lang('layout.lang.title')">@lang('layout.lang.txt')</a>
				</li>

			</ul>
		</div>
	</nav>
	@yield('content')
	<h2 class="text-center nopadding">@lang('layout.contact')</h2>
	<footer style="background-image: url({{asset('images/2000/footer.jpg')}})">

		<div class="flex">
			<div class="one">
				<div class="contact">
					<div class="w-100 d-flex justify-content-center">
						<img class="" src="{{ asset('images/Logoblack.png') }}">
					</div>
					<div class="text-center">
						<div class="ligne">
							<span class="iconify" data-icon="ant-design:mail-outlined" data-inline="false"></span>

							<a href="mailto:contact@artdelapierre.net">contact@artdelapierre.net</a>
						</div>
						<div class="ligne">
							<span class="iconify" data-icon="bi:phone" data-inline="false"></span>
							<a href="tel:0784024325">07 84 02 43 25</a>
						</div>
					</div>
				</div>
			</div>
			<div class="two">
				<div class="map" id="mapid">
				</div>
			</div>

		</div>
	</footer>
	<div class="copy">
		<p>©{{ now()->year }} Les Petites Mains du Limousin</p>
		<p>Site réalisé avec ❤️ par <a href="https://latoile.dev">LaToile.dev</a></p>
		<p><a href="{{ route('mentions') }}">Mentions Légales</a></p>
	</div>
</body>
</html>